### ISSUE TITLE
Машинное зрение

### ISSUE THREAD

**Issue by iAmFoxik** [iAmFoxik/kuka-server#1]
# ToDo [Обучающая модель]
- [ ] Загрузить модели из kaggle
- [ ] Подготовить картинки для загрузки в модель
- [ ] Настроить нейронную сеть
- [ ] Обучить систему
- [ ] Прогнать тестовые данные через модель
